// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nrqbqrextfpjoogovizh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ycWJxcmV4dGZwam9vZ292aXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTk4ODYsImV4cCI6MjA2OTM5NTg4Nn0.cbPY27ns13AosNpSKT1EY4A4ungbHW9n827Z3zyLfCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);